services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: 21TQIbxpu3LP
      POSTGRES_DB: trello
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      POSTGRES_URL: postgres://postgres:21TQIbxpu3LP@postgres:5432/trello
    develop:
      watch:
      - action: sync
        path: ./src
        target: /app
        ignore:
          - venv/
      - action: rebuild
        path: ./src