services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 21TQIbxpu3LP
      POSTGRES_DB: trello
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8000
    environment:
      POSTGRES_URL: postgres://postgres:21TQIbxpu3LP@postgres:5432/trello